export declare enum SecurityEvent {
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILED = "LOGIN_FAILED",
    LOGOUT = "LOGOUT",
    TOKEN_REFRESH = "TOKEN_REFRESH",
    TOKEN_REVOKED = "TOKEN_REVOKED",
    PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",
    PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED",
    PASSWORD_CHANGED = "PASSWORD_CHANGED",
    EMAIL_VERIFIED = "EMAIL_VERIFIED",
    EMAIL_VERIFICATION_REQUESTED = "EMAIL_VERIFICATION_REQUESTED",
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
    ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED",
    FORBIDDEN_ACCESS = "FORBIDDEN_ACCESS",
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
    SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
    SESSION_EXPIRED = "SESSION_EXPIRED",
    SESSION_REVOKED = "SESSION_REVOKED",
    PROFILE_UPDATED = "PROFILE_UPDATED",
    ROLE_CHANGED = "ROLE_CHANGED",
    USER_DELETED = "USER_DELETED",
    USER_DEACTIVATED = "USER_DEACTIVATED"
}
export declare class AuditLogger {
    private readonly logger;
    log(event: SecurityEvent, userId: string | null, details?: Record<string, any>, ip?: string): void;
    private sanitize;
    private writeToAuditStore;
}
